-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua

-- Add additional keymaps
vim.keymap.set("n", "<leader>w-", "<C-W>s", { desc = "Split Window Below", remap = true })
vim.keymap.set("n", "<leader>w|", "<C-W>v", { desc = "Split Window Right", remap = true })
vim.keymap.set("n", "<leader>qd", '<Cmd>lua MiniSessions.select("delete")<CR>', { desc = "Delete" })
vim.keymap.set("n", "<leader>qn", '<Cmd>lua MiniSessions.write(vim.fn.input("Session name: "))<CR>', { desc = "New" })
vim.keymap.set("n", "<leader>qr", '<Cmd>lua MiniSessions.select("read")<CR>', { desc = "Read" })
vim.keymap.set("n", "<leader>qw", "<Cmd>lua MiniSessions.write()<CR>", { desc = "Write current" })
vim.keymap.set("i", "<C-h>", "<Left>")
vim.keymap.set("i", "<C-l>", "<Right>")
vim.keymap.set("i", "<C-BS>", "<C-w>")
vim.keymap.set("i", "<S-BS>", "<C-w>")
vim.keymap.set("n", "<S-h>", "12<Left>")
vim.keymap.set("n", "<S-l>", "12<Right>")

-- Remove default keymaps
vim.keymap.del("n", "<leader>K")
vim.keymap.del("n", "<leader>l")
vim.keymap.del("n", "<leader>L")
vim.keymap.del("n", "<leader>`")
vim.keymap.del("n", "<leader>-")
vim.keymap.del("n", "<leader>|")
vim.keymap.del("n", "<leader>/")
vim.keymap.del("n", "<leader>:")
vim.keymap.del("n", "<leader><space>")
vim.keymap.del("n", "<leader>fT")
vim.keymap.del("n", "<leader>ft")
vim.keymap.del("n", "<leader><tab>l")
vim.keymap.del("n", "<leader><tab>o")
vim.keymap.del("n", "<leader><tab>f")
vim.keymap.del("n", "<leader><tab><tab>")
vim.keymap.del("n", "<leader><tab>]")
vim.keymap.del("n", "<leader><tab>d")
vim.keymap.del("n", "<leader><tab>[")
vim.keymap.del("n", "<leader>?")
